POST http://localhost:8080/api/post-job
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE2OTk5NDE2OTJ9.u98AkjkYBNA_9XgzIvtE49pw0sD0fSsZxABx6C6_3PqRN_10oaGoXGqW2NLysFfkR0O5uOJ5vaZlkAwbjavoBg

{
  "title" : "제목",
  "content": "내용",
  "payment": 1231323,
  "address" : "동산동 159-25"
}

###
GET https://kkori.kr/api/post/all
Content-Type: application/json