POST localhost:8080/api/post-job
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDA2MjA0MTZ9.zi5s9VaaKmfEK_qEOewyLkqmKIiG-r2VB7Z1TlSsQNmuIW0MqN_xdRNZI-0N0fu7sLqbWiWTxf4kWbPgYskvvg

{
  "title" : "태빈이",
  "content": "산책부탁요",
  "payment": 1000,
  "address" : "치평동 573-1",
  "dogIds": [1,2]
}
###
GET localhost:8080/api/post/all
Content-Type: application/json

###
POST localhost:8080/api/reserved-job/reserve/xodnjs8287/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDA2MjA0MTZ9.zi5s9VaaKmfEK_qEOewyLkqmKIiG-r2VB7Z1TlSsQNmuIW0MqN_xdRNZI-0N0fu7sLqbWiWTxf4kWbPgYskvvg
Content-Type: application/json

###
POST http://localhost:8080/api/job-board/like/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDAxODU3MjV9.64d82GLA82XxjExV_m_XAt5JY7-g3p4e0nYoi6o0oePLDQDXSu0wptyTfxwANRmTfFaQ8jCBPu4RssKddUcVJQ
###
GET http://localhost:8080/api/job-board/like/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDAxODU3MjV9.64d82GLA82XxjExV_m_XAt5JY7-g3p4e0nYoi6o0oePLDQDXSu0wptyTfxwANRmTfFaQ8jCBPu4RssKddUcVJQ
###
DELETE http://localhost:8080/api/job-board/like/delete-like/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDAxODU3MjV9.64d82GLA82XxjExV_m_XAt5JY7-g3p4e0nYoi6o0oePLDQDXSu0wptyTfxwANRmTfFaQ8jCBPu4RssKddUcVJQ
###
GET http://localhost:8080/api/reserved-job/all/by-sitter
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDA2MjA0MTZ9.zi5s9VaaKmfEK_qEOewyLkqmKIiG-r2VB7Z1TlSsQNmuIW0MqN_xdRNZI-0N0fu7sLqbWiWTxf4kWbPgYskvvg
###
GET http://localhost:8080/api/walk/detail/by-sitter/1
Content-Type: application/json