POST localhost:8080/api/auth/naver
Content-Type: application/json

{
  "authorizationCode": "XRwepmrjcd36eb4eSY",
  "state": null
}

###
GET localhost:8080/api/member/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE2OTk1MTQ3NTh9.R2x13WP5_I-KKSmFAWBxSdzsj1L4HOSTsmQ3OwTFkHaIsX6H1wPZabORTWS48A67TD_qyLJ198mRS_5UAjZ8xQ

###
POST localhost:8080/api/member/register-device
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE2OTk1MTQ3NTh9.R2x13WP5_I-KKSmFAWBxSdzsj1L4HOSTsmQ3OwTFkHaIsX6H1wPZabORTWS48A67TD_qyLJ198mRS_5UAjZ8xQ
Content-Type: application/json

{
  "deviceNumber": "123122"
}

###
PUT localhost:8080/api/member/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDAxODU3MjV9.64d82GLA82XxjExV_m_XAt5JY7-g3p4e0nYoi6o0oePLDQDXSu0wptyTfxwANRmTfFaQ8jCBPu4RssKddUcVJQ

{
  "nickName": "나는짱짱맨"
}

###
PUT localhost:8080/api/member/image/update
Content-Type: multipart/form-data;
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDAxODU5OTV9._MU28tMvPF5K-2nY4HWPYKr6fTEyA25wc7muZ21AfXhA2R9p47BtIX0PM8n7jTIWcAwZSIUi3Bcp1hL6XkIwMA


###
GET localhost:8080/api/member/detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE2OTk1MTQ3NTh9.R2x13WP5_I-KKSmFAWBxSdzsj1L4HOSTsmQ3OwTFkHaIsX6H1wPZabORTWS48A67TD_qyLJ198mRS_5UAjZ8xQ
Content-Type: application/json