POST localhost:8080/api/auth/naver
Content-Type: application/json

{
  "authorizationCode": "ObpxKzxbVzxsyYDLyU",
  "state": null
}

###
GET localhost:8080/api/member/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE2OTk1MTQ3NTh9.R2x13WP5_I-KKSmFAWBxSdzsj1L4HOSTsmQ3OwTFkHaIsX6H1wPZabORTWS48A67TD_qyLJ198mRS_5UAjZ8xQ

###
POST localhost:8080/api/member/register-device
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDA2NDI1ODJ9.dyc7a4An-RkYHDAiqzXhZd-OU8SMiLNTqoCghlK55ngBXFWaDZKtV6t3-qltmesxC_Ln7mrjMgh-G4yKTxnAqw
Content-Type: application/json

{
  "deviceNumber": "123456"
}

###
PUT https://kkori.kr/api/member/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDA1NDk3MjB9.f6fHH9FlD8X5OL-0wZUaShrw1D5utw6Y36OAXh2Oey2xXx_l3MKtSSqWK56yw9TftaU_X_UAqNhpTDz-kX8ZMw

{
  "nickName": "나는짱짱맨23"
}

###
PUT localhost:8080/api/member/image/update
Content-Type: multipart/form-data;
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6InVzZXIiLCJleHAiOjE3MDAxODU5OTV9._MU28tMvPF5K-2nY4HWPYKr6fTEyA25wc7muZ21AfXhA2R9p47BtIX0PM8n7jTIWcAwZSIUi3Bcp1hL6XkIwMA


###
GET localhost:8080/api/member/detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6InVzZXIiLCJleHAiOjE2OTk1MTQ3NTh9.R2x13WP5_I-KKSmFAWBxSdzsj1L4HOSTsmQ3OwTFkHaIsX6H1wPZabORTWS48A67TD_qyLJ198mRS_5UAjZ8xQ
Content-Type: application/json